// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	lift "anujkumar.com/elevator/lift"
	mock "github.com/stretchr/testify/mock"

	models "anujkumar.com/elevator/models"
)

// ILift is an autogenerated mock type for the ILift type
type ILift struct {
	mock.Mock
}

// Assign provides a mock function with given fields: _a0, _a1
func (_m *ILift) Assign(_a0 context.Context, _a1 models.Request) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Request) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrentFloor provides a mock function with given fields: _a0
func (_m *ILift) GetCurrentFloor(_a0 context.Context) models.Floor {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentFloor")
	}

	var r0 models.Floor
	if rf, ok := ret.Get(0).(func(context.Context) models.Floor); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Floor)
	}

	return r0
}

// GetNextStop provides a mock function with given fields: _a0
func (_m *ILift) GetNextStop(_a0 context.Context) (models.Floor, lift.LiftState) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetNextStop")
	}

	var r0 models.Floor
	var r1 lift.LiftState
	if rf, ok := ret.Get(0).(func(context.Context) (models.Floor, lift.LiftState)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.Floor); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Floor)
	}

	if rf, ok := ret.Get(1).(func(context.Context) lift.LiftState); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(lift.LiftState)
	}

	return r0, r1
}

// GetState provides a mock function with given fields: _a0
func (_m *ILift) GetState(_a0 context.Context) lift.LiftState {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 lift.LiftState
	if rf, ok := ret.Get(0).(func(context.Context) lift.LiftState); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(lift.LiftState)
	}

	return r0
}

// MoveToNextStop provides a mock function with given fields: _a0
func (_m *ILift) MoveToNextStop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MoveToNextStop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Operate provides a mock function with given fields: _a0
func (_m *ILift) Operate(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Operate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILift creates a new instance of ILift. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILift(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILift {
	mock := &ILift{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
